module.exports = {
  apps: [
    {
      name: 'testforge-backend',
      cwd: 'C:\\project\\TestForge\\TestForge\\server',
      script: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      args: '-m uvicorn main:app --host 0.0.0.0 --port 8000',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\backend-error.log',
      out_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\backend-out.log',
    },
    {
      name: 'testforge-celery-worker',
      cwd: 'C:\\project\\TestForge\\TestForge\\server',
      script: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      args: '-m celery -A celery_app worker --loglevel=info',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\celery-worker-error.log',
      out_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\celery-worker-out.log',
    },
    {
      name: 'testforge-celery-beat',
      cwd: 'C:\\project\\TestForge\\TestForge\\server',
      script: 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      args: '-m celery -A celery_app beat --loglevel=info',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\celery-beat-error.log',
      out_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\celery-beat-out.log',
    },
    {
      name: 'testforge-frontend',
      cwd: 'C:\\project\\TestForge\\TestForge\\frontend',
      script: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
      args: 'run dev',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\frontend-error.log',
      out_file: 'C:\\project\\TestForge\\TestForge\\deploy\\logs\\frontend-out.log',
    },
  ],
}
